- hosts: all
  tasks:
  - yum:
      name: httpd
      state: present
  - service:
      name: httpd
      enabled: true
      state: started
  - copy:
      content: "<h1> hello world </h1>"
      dest: /var/www/html/index.html
